name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main # Atau branch yang Anda inginkan untuk trigger deployment

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      # Opsional: Jika Anda perlu menjalankan npm install dan build (misalnya untuk Vite)
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18' # Sesuaikan dengan versi Node.js Anda

      # - name: Install NPM dependencies
      #   run: npm install

      # - name: Build assets
      #   run: npm run build

      - name: Build and Push Docker image
        run: |-
          gcloud builds submit --tag ${{ secrets.IMAGE_NAME }}:${{ github.sha }} .

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --image ${{ secrets.IMAGE_NAME }}:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            # Tambahkan --set-env-vars atau --update-secrets di sini jika perlu
            # Contoh: --set-env-vars APP_ENV=production,APP_DEBUG=false
            # Untuk database, idealnya gunakan Cloud SQL Proxy dan secrets manager
            # --set-env-vars DB_CONNECTION=mysql,DB_SOCKET="/cloudsql/${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:NAMA_INSTANCE_SQL"
            # --update-secrets=DB_USERNAME=DB_USERNAME_SECRET:latest,DB_PASSWORD=DB_PASSWORD_SECRET:latest